<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Nuspec\contentFiles\any\any\Platz.Cosmos.Link\**" />
    <EmbeddedResource Remove="Nuspec\contentFiles\any\any\Platz.Cosmos.Link\**" />
    <None Remove="Nuspec\contentFiles\any\any\Platz.Cosmos.Link\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Nuspec\contentFiles\any\any\Platz.Cosmos.Link\appsettings.cosmos.json" />
    <Content Include="Nuspec\contentFiles\any\any\Platz.Cosmos.Link\readme.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.46.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\flows\BlazorForms.Flows.Definitions\BlazorForms.Flows.Definitions.csproj" />
    <ProjectReference Include="..\BlazorForms.Platform.Definitions\BlazorForms.Platform.Definitions.csproj" />
  </ItemGroup>


</Project>
